"use client"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./styles/globals.css"
import "@mantine/core/styles.css"
import {
    MantineProvider,
    ColorSchemeScript,
    createTheme,
    AppShell,
    Container,
} from "@mantine/core"
// import Header from "./header/page"
import "@mantine/notifications/styles.css"
import HeaderComponent from "./components/HeaderComponent"

// const inter = Inter({ subsets: ["latin"] })
const theme = createTheme({
    fontFamily: "Poppins, sans-serif",
})

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={theme}>
                    <AppShell
                        header={{ height: { base: 60, md: 70, lg: 80 } }}
                        padding="md">
                        <AppShell.Header style={{ opacity: 0.9 }}>
                            <Container size="xl">
                                <HeaderComponent />
                            </Container>
                        </AppShell.Header>
                        <AppShell.Main>
                            <Container size="xl">{children}</Container>
                        </AppShell.Main>
                    </AppShell>
                </MantineProvider>
            </body>
        </html>
    )
}
